### ISSUE TITLE
[Bug]: We should remove config.js of the repos

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/DEV-NFT#49]
### Detailed Description

I found this error in this project where we expose our marketplace address. We should remove it.

### Expected Behavior

I expected that it was masked.

### How can someone reproduce the behavior?

1. Delete config.js
2. Make env var

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
You already know me, bot.

**Comment by KukretiShubham** [comment]
exposing marketplace addresses is not a security issue. Also, we will be bringing a new contract for the mainnet.
