### ISSUE TITLE
[Feat]: Improve NFT design

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/DEV-NFT#50]
### Detailed Description

I think the feature should be added because actual NFT are quick-made for the hackaton purpose (thanks to @KukretiShubham) and it's not so fancy.

Let this issue open to discuss about the design, and we should ask the community to vote.

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhinavMV** [comment]
Can we let users decide what to show on the NFT.
For eg - let users upload a jpeg file(with filename- repo name) in the repo and show this jpeg on the card design.
If no such file is present then we can show a default card design
[Just like github does i.e if repo with account name is present github shows description else it does not]
Not sure if this is possible 🤔
