### ISSUE TITLE
[Feat]: Make dashboard accessible through landing page

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/DEV-NFT#51]
### Detailed Description

As requested by Shubham.

Making it accessible through our landing page can attract people to buy NFT or look to the onboarded projects.

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhinavMV** [comment]
Like add a marketplace button beside the login button?
(Dashboard is accessible from landing page in mobile view)

**Comment by vinzvinci** [comment]
> Like add a marketplace button beside the login button? (Dashboard is accessible from landing page in mobile view)

What do u think @KukretiShubham?
