### ISSUE TITLE
[Feat]: Steps to get environment variables

### ISSUE THREAD

**Issue by KukretiShubham** [WebXDAO/DEV-NFT#62]
### Detailed Description

For local development, the dev would need a .env file. We should explain how they can get their own env variables in the Readme.
cc @mkubdev 
```
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
NEXTAUTH_URL=http://localhost:3000
```

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Maybe we can make quick explenation of how to generate GitHub OAuth Apps creds on the readme ?

**Comment by KukretiShubham** [comment]
yes

**Comment by hyomiTheTech** [comment]
Can I work on this issue?

**Comment by mkubdev** [comment]
Hi @hyomiTheTech ! Yes sure; i assign you.

**Comment by hyomiTheTech** [comment]
This issue is now solved with my recent PR.

**Comment by shuklaritvik06** [comment]
> This issue is now solved with my recent PR.

Yes thanku 🚀

**Comment by hyomiTheTech** [comment]
> > This issue is now solved with my recent PR.
> 
> Yes thanku 🚀

Thank you! 🚀🚀🚀
