### ISSUE TITLE
[Bug]: update the copyright year to 2022 in both license and websites footer

### ISSUE THREAD

**Issue by unnikrishnan2002** [WebXDAO/DEV-NFT#63]
### Detailed Description

--

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shuklaritvik06** [comment]
For website footer, it can be done, but for license year I am not sure as it is the part of the license
![ss](https://user-images.githubusercontent.com/72812470/148105674-0601032a-97b6-45fe-80e5-4b76a29c5dfc.png)
 
@krishguptadev / @vinzvinci  opinion?
