### ISSUE TITLE
[Feat]: Addition in README.md

### ISSUE THREAD

**Issue by AlphaVS-76** [WebXDAO/DEV-NFT#79]
### Detailed Description

I think the feature [Inline Links] should be added because in the [README.md](https://github.com/WebXDAO/DEV-NFT/blob/main/README.md) file, there are URLs which can be made to look more static and easy-to-read if made into inline links.
Also, The [Contributing Guidelines](https://github.com/WebXDAO/DEV-NFT/blob/main/CONTRIBUTING.md) page can be improved as I have observed a few errors in regards to the terms used.

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Anything else?

I would be very glad to be assigned this issue!

**Comment by krshdev** [comment]
Thanks for reporting this issue @AlphaVS-76, I'll assign you as per your message in the "Anything else?" section
