### ISSUE TITLE
[Bug]: Text overlap in cards

### ISSUE THREAD

**Issue by Sreekar-Shodhan** [WebXDAO/DEV-NFT#96]
### Detailed Description

I found this error in this project where ,In the home page the text inside the cards are overlapping on the buy button . 

![image](https://user-images.githubusercontent.com/71596539/169260983-5693ddfc-4c5b-411d-8a3d-9c0e3075ed95.png)

### Expected Behavior

I expected that... the text and buy button have some gap/ space between them

### How can someone reproduce the behavior?

1. Go to... Home page
2. Do...Login
3. Now...You see the error visible 
4. Finally...

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pranay202** [comment]
I would like to work on this issue.
